# Generated by Django 5.0.6 on 2024-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='surname',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='twitter',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
