# Generated by Django 5.0.6 on 2024-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_technologies_topic_project_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='miniDesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(default='N/A', null=True, to='base.technologies'),
        ),
    ]
